version: "3.6"
services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    ports: 
      - 3300:3300
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=employee_database
    networks: 
      - employee-network
    volumes:
      - ./mysqldb:/var/lib/mysql
      - ./dbscripts:/docker-entrypoint-initdb.d
  
  eureka:
      image: eureka-server
      build: ./eureka-server
      container_name: eureka-server
      ports: 
        - 8761:8761
      networks: 
      - employee-network
  zuul:
    image: zuul-service
    build: ./zuul
    container_name: zuul-service
    ports: 
      - 8762:8762
    depends_on: 
      - db
      - eureka
    networks: 
      - employee-network
  
  authentication:
      image: authentication-service
      build: ./authentication-service
      container_name: authentication-service
      ports: 
        - 8763:8763
      depends_on: 
        - db
        - eureka
        - zuul
      networks: 
      - employee-network
      
  employee-service:
      image: employee-service
      build: ./employee-service
      container_name: employee-service
      ports: 
        - 8090:8090
      depends_on: 
        - db
        - eureka
        - zuul
      networks: 
        - employee-network
      # entrypoint: ./wait-for-it.sh db:3306 --echo "mysql is up"

networks:
  employee-network:
    name: employee-network